config/routes.rb
Rails.application.routes.draw do

  get 'locations/new'

  get 'locations/directions'

  resources :admin



  resources :suppliers
  resources :locations
  resources :resources

  # resources :users

  # resources :admin
  devise_for :users, controllers: {
     sessions: 'users/sessions'
   }
     # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'locations#index'

end

app/views/resources/_form.html.erb
<%= form_for(resource) do |f| %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type_of %>
    <%= f.text_field :type_of %>
  </div>

  <div class="field">
    <%= f.label :stock %>
    <%= f.text_field :stock %>
  </div>

  <div class="field">
    <%= f.label :units %>
    <%= f.text_field :units %>
  </div>

  <% if params[:location] %>
  <input type="hidden" id="resource_location_id" name="resource[location_id]" value="<%= params[:location] %>" />
<% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>
<p>@resource.location.supplier.user.id <br>
<%= @resource.location.supplier.user %>
</p>
<% if current_user.admin? %>
<%= render 'form', resource: @resource %>
<% else %>
Not authorized
<% end %>
<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resources</h1>

<table class="table">
  <thead>
    <tr>
      <th>Location</th>
      <th>Supplier</th>
      <th></th>
      <th>Type</th>
      <th>Stock</th>
      <th>Units</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.location.name %></td>
        <td><%= resource.location.supplier.name %></td>
        <td><img src="<%= resource.location.supplier.avatar.url %>" alt="<%= resource.location.supplier.name%>" height="30px">
          </td>
        <td><%= resource.type_of %></td>
        <td><%= resource.stock %></td>
        <td><%= resource.units %></td>
        <td><%= link_to 'Show', resource %></td>
        <% if policy(resource).edit? %>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <% end %>
        <% if policy(resource).destroy? %>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

Add new resources via locations

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @resource.type_of %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @resource.stock %>
</p>

<p>
  <strong>Units:</strong>
  <%= @resource.units %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>