config/routes.rb
Rails.application.routes.draw do

  get 'locations/new'

  get 'locations/directions'

  resources :admin



  resources :suppliers
  resources :locations
  resources :resources

  # resources :users

  # resources :admin
  devise_for :users, controllers: {
     sessions: 'users/sessions'
   }
     # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'locations#index'

end

app/views/layouts/_login_items.html.erb
<% if user_signed_in? %>
  <%= link_to("Logout #{current_user.email}", destroy_user_session_path, :method => :delete) %>
<% else %>
  <%= link_to('Login', new_user_session_path)  %>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand">Water Walk</a>
      <!-- <img class="navbar-left" alt="Logo" src="/assets/LambLogoTextHorz.png" style="height: 50px" /> -->
      <%#=link_to cl_image_tag("LambLogoTextHorz_jro4vz.png"), root_path, class: "navbar-left logo-img"%>

    </div>
    <ul class="nav navbar-nav">
      <li class="<%= 'active' if params[:controller] == 'locations' %>"><%= link_to "Home", root_path %></li>
      <li class="<%= 'active' if params[:controller] == 'suppliers' %>"><%= link_to "Suppliers", suppliers_path %></li>
      <li class="<%= 'active' if params[:controller] == 'resources' %>"><%= link_to "Resources", resources_path %></li>

      <% if current_user
        if current_user.admin? %>
        <li class="<%= 'active' if params[:controller] == 'admin' %>"><%= link_to 'Admin', admin_index_url %></li>
      <% end %>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= render 'layouts/login_items' %></li>
      <li><%= render 'layouts/registration_items' %></li>
    </ul>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% flash.each do |key, value| %>
      <div class="alert alert-<%=key%>">
            <%= value %>
      </div>
<% end %>

app/views/layouts/_registration_items.html.erb
<% if user_signed_in? %>
  <%= link_to('Edit registration', edit_user_registration_path) %>
<% else %>
  <%= link_to('Register', new_user_registration_path)  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WaterWalk</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'http://maps.google.com/maps/api/js?key=AIzaSyBbzHf-PPjzFjiNoRTSjbQ6VTt6zXZMZMA&libraries=places' %>

    <%#= javascript_include_tag 'https://code.jquery.com/jquery-1.10.2.min.js' %>
    <%= javascript_include_tag('locationpicker.jquery.min.js') %>
  </head>

  <body>
    <%= render 'layouts/nav' %>





      <div class="container">
        <%= render partial: 'layouts/notice', flash: flash %>
        <%= yield %>
      </div>
  </body>
</html>